### ISSUE TITLE
Project licence?

### ISSUE THREAD

**Issue by ns-vmaisonneuve** [patrick91/rich-toolkit#16]
Hi, I was wondering what the license for this project is. It gets pulled in by `fastapi[standard]`, and I'd like to check if it can be used in commercial software.

**Comment by patrick91** [comment]
@ns-vmaisonneuve yup, I'll make MIT now, I forgot to add it 😊

**Comment by patrick91** [comment]
@ns-vmaisonneuve just updated, and made a new release too (just in case it is needed)

Thanks for opening the issue!

**Comment by ns-vmaisonneuve** [comment]
@patrick91 Thanks a lot!
